"""Add user topic favorites table

Revision ID: 7c8255f6d397
Revises: 1525509e25d2
Create Date: 2025-07-05 23:18:01.696067

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "7c8255f6d397"
down_revision: Union[str, None] = "1525509e25d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
