"""Add user topic favorites table

Revision ID: e215637efb6f
Revises: ab1164608d35
Create Date: 2025-07-05 23:18:01.696067

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e215637efb6f"
down_revision: Union[str, None] = "ab1164608d35"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
