name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v4

      # Frontend Build
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 10.12.4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('frontend/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install pnpm deps
        working-directory: ./frontend
        run: pnpm install --frozen-lockfile
      - name: Build frontend
        working-directory: ./frontend
        run: pnpm run build

      # Backend Start Check
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"
          cache: "pip"
      - name: Install backend deps
        run: |
          pip install -r backend/requirements.txt uvicorn
      - name: Start backend
        run: |
          timeout 10s python -m uvicorn backend.app:app --host 0.0.0.0 --port 8000 || true
