name: Test

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    needs: lint
    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        ports: ["5432:5432"]
        options: >-
          --health-cmd="pg_isready -U postgres"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    strategy:
      matrix:
        python: ["3.11", "3.12"]
        node: ["22"]

    steps:
      - uses: actions/checkout@v4

      # Python Tests
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
          cache: "pip"
      - name: Install Python deps
        run: pip install -r backend/requirements.txt pytest pytest-cov mypy
      - name: Type check
        run: cd backend && mypy .
      - name: Pytest
        run: cd backend && pytest --cov=app --cov-report=xml --cov-fail-under=90
      - name: Upload backend coverage
        uses: codecov/codecov-action@v3
        with:
          file: backend/coverage.xml
          flags: backend
          fail_ci_if_error: true

      # Node Tests
      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: "pnpm"
          cache-dependency-path: "./frontend/pnpm-lock.yaml"
      - name: Install pnpm deps
        working-directory: ./frontend
        run: pnpm install
      - name: Unit tests
        working-directory: ./frontend
        run: pnpm test:unit --coverage
      - name: Integration tests
        working-directory: ./frontend
        run: pnpm test:integration
      - name: Upload frontend coverage
        uses: codecov/codecov-action@v3
        with:
          file: frontend/coverage/coverage-final.json
          flags: frontend
          fail_ci_if_error: true
